apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: three-tier-app-qa

resources:
  - ../base

nameSuffix: -qa

commonLabels:
  environment: qa

patchesStrategicMerge:
  - patches/replica-patch.yaml
  - patches/resource-limits.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - NODE_ENV=qa
