apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: three-tier-app
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: three-tier-app
spec:
  replicas: 2
